### PR TITLE
Add + apply pre-commit

### PR DESCRIPTION
**Pull request by marksverdhei**
What is better than a linter?
A linter and a formatter

What is better than asking your contributors to sort imports?
Isort

### CODE REVIEW

**Comment by LBlend** [comment]
I tried formatting the code to make the linter happy but then black decided to reformat my "fix", making the linter mad at me.

I have a feeling this is gonna annoy the shit out of me at some point

image

I'll end up ignoring the error in question for now but we should figure out how to avoid this

**Comment by marksverdhei** [comment]
> I tried formatting the code to make the linter happy but then black decided to reformat my "fix", making the linter mad at me.
> 
> I have a feeling this is gonna annoy the shit out of me at some point
> 
> image
> 
> I'll end up ignoring the error in question for now but we should figure out how to avoid this

@LBlend you can increase the max length in black to avoid these

**Comment by LBlend** [comment]
> > I tried formatting the code to make the linter happy but then black decided to reformat my "fix", making the linter mad at me.
> > I have a feeling this is gonna annoy the shit out of me at some point
> > image
> > I'll end up ignoring the error in question for now but we should figure out how to avoid this
> 
> @LBlend you can increase the max length in black to avoid these

ah yes, makes sense. I'll do that then 👍

**Comment by LBlend** [comment]
finally I got this shit working. No idea if it will fuck something up in the future but we ballin'

**Pull request merged**
